const inventoryModelSeeder = [
    {
      name: "Wireless Keyboard",
      description: "Compact wireless keyboard with ergonomic design",
      sku: "KB1234",
      quantity: 50,
      price: 29.99,
      category: "Accessories",
      supplier: "Tech Supplies Co.",
      status: true,
      lowStockThreshold: 10,
      barcode: "1234567890123",
      location: "Aisle 3, Shelf B",
      CreatedAt:Date.now(),
      UpdatedAt:Date.now(),
    },
    {
      name: "Gaming Mouse",
      description: "High-precision gaming mouse with RGB lighting",
      sku: "GM5678",
      quantity: 75,
      price: 49.99,
      category: "Accessories",
      supplier: "Gaming Gear Inc.",
      status: true,
      lowStockThreshold: 15,
      barcode: "1234567890456",
      location: "Aisle 3, Shelf C",
      CreatedAt:Date.now(),
      UpdatedAt:Date.now(),
    },
    {
      name: "Laptop Stand",
      description: "Adjustable aluminum laptop stand",
      sku: "LS9101",
      quantity: 30,
      price: 34.99,
      category: "Office Supplies",
      supplier: "Workspace Solutions",
      status: true,
      lowStockThreshold: 5,
      barcode: "1234567890789",
      location: "Aisle 2, Shelf A",
      CreatedAt:Date.now(),
      UpdatedAt:Date.now(),
    },
    {
      name: "Noise Cancelling Headphones",
      description: "Over-ear headphones with active noise cancellation",
      sku: "NC1122",
      quantity: 20,
      price: 129.99,
      category: "Electronics",
      supplier: "Audio World",
      status: true,
      lowStockThreshold: 5,
      barcode: "1234567890912",
      location: "Aisle 4, Shelf D",
      CreatedAt:Date.now(),
      UpdatedAt:Date.now(),
    },
    {
      name: "USB-C Hub",
      description: "7-in-1 USB-C hub with HDMI and Ethernet ports",
      sku: "USBC6789",
      quantity: 40,
      price: 39.99,
      category: "Accessories",
      supplier: "Connectivity Experts",
      status: true,
      lowStockThreshold: 10,
      barcode: "1234567890124",
      location: "Aisle 5, Shelf E",
      CreatedAt:Date.now(),
      UpdatedAt:Date.now(),
    },
    {
      name: "External Hard Drive",
      description: "1TB portable external hard drive",
      sku: "EHD3456",
      quantity: 25,
      price: 59.99,
      category: "Storage",
      supplier: "DataSecure",
      status: false,
      lowStockThreshold: 8,
      barcode: "1234567890345",
      location: "Aisle 6, Shelf A",
      CreatedAt:Date.now(),
      UpdatedAt:Date.now(),
    },
    {
      name: "Smartphone Tripod",
      description: "Flexible tripod for smartphones and small cameras",
      sku: "TP7890",
      quantity: 45,
      price: 19.99,
      category: "Accessories",
      supplier: "Photo Essentials",
      status: false,
      lowStockThreshold: 10,
      barcode: "1234567890567",
      location: "Aisle 7, Shelf B",
      CreatedAt:Date.now(),
      UpdatedAt:Date.now(),
    },
    {
      name: "Portable Power Bank",
      description: "10000mAh portable power bank",
      sku: "PB4321",
      quantity: 60,
      price: 24.99,
      category: "Electronics",
      supplier: "Energy Solutions",
      status: true,
      lowStockThreshold: 12,
      barcode: "1234567890780",
      location: "Aisle 8, Shelf C",
      CreatedAt:Date.now(),
      UpdatedAt:Date.now(),
    },
    {
      name: "Desk Organizer",
      description: "Multi-compartment desk organizer",
      sku: "DO3456",
      quantity: 35,
      price: 14.99,
      category: "Office Supplies",
      supplier: "Workspace Solutions",
      status: true,
      lowStockThreshold: 8,
      barcode: "1234567890891",
      location: "Aisle 2, Shelf B",
      CreatedAt:Date.now(),
      UpdatedAt:Date.now(),
    },
    {
      name: "LED Desk Lamp",
      description: "Dimmable LED desk lamp with USB charging port",
      sku: "LD6789",
      quantity: 30,
      price: 49.99,
      category: "Office Supplies",
      supplier: "Lighting Innovations",
      status: true,
      lowStockThreshold: 6,
      barcode: "1234567890321",
      location: "Aisle 9, Shelf A",
      CreatedAt:Date.now(),
      UpdatedAt:Date.now(),
    },
  ];
  export default inventoryModelSeeder